//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_img { get; set; }
        public string pro_descrip { get; set; }
        public int pro_price { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
        public Nullable<int> pro_fk_usr { get; set; }
    
        public virtual category category { get; set; }
        public virtual usr usr { get; set; }
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
